version: "3"

dotenv:
  - ".env"

tasks:
  default:
    desc: "show all available tasks"
    cmds:
      - task --list-all
    silent: true

  tidy:
    desc: install pkg listed in go.mod
    cmds:
      - go mod tidy

  test:
    desc: running test
    cmds:
      - go test ./...

  coverage:
    desc: check test coverage
    cmds:
      - mkdir -p test/coverage
      - go test -cover ./... -coverprofile=test/coverage/coverage.out
      - go tool cover -html=test/coverage/coverage.out -o test/coverage/coverage.html

  lint:
    desc: run golangci-lint
    cmds:
      - golangci-lint run --timeout 5m --config .golangci.yml
